version: '3.3'
services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      -
        type: bind
        source: ${DATABASE_SOURCE}
        target: /var/lib/postgresql/data
    networks:
      - reference
networks:
  reference: